/**
 * The OSM geometry: what it must be, and what it must not cost.
 *
 * `fixtures/geo/*.json` is generated by `tools/geo/generate.ts` and committed.
 * Generated data is exactly the kind that rots quietly — a regeneration with a
 * transposed bbox draws a confident map of the wrong sea, and a regeneration at
 * the wrong tolerance triples the bytes without changing a single rendered
 * pixel. Neither shows up in a typecheck, because the files are JSON and the
 * loader casts them once (`fixtures/geo/index.ts` says why).
 *
 * Three groups of assertion, and the third is the licence one.
 */

import { describe, expect, test } from "bun:test";
import { gzipSync } from "bun";
import { existsSync, readFileSync } from "fs";
import { join, resolve } from "path";

import { OSM_ATTRIBUTION, geo, geoIds } from "../fixtures/geo/index.js";
import { mapScenes } from "../fixtures/places.js";

const KIT = resolve(import.meta.dir, "..");
const GEO = join(KIT, "fixtures", "geo");

/** The same basin the rest of the world is checked against: a transposed
 * `[lat, lon]` pair lands outside it, which a spot check does not catch
 * because at these latitudes the two ranges overlap. */
const BASIN = { lat: [30, 46], lon: [-6, 37] } as const;

describe("the geometry is geometry", () => {
  test("every location loaded", () => {
    // A guard on the guard: an empty set would pass every loop below.
    expect(geoIds).toEqual(["ithaca", "gozo", "corfu", "messina", "troy"]);
  });

  for (const id of geoIds) {
    const fixture = geo[id];

    test(`${id}: every coordinate is a pair inside the Mediterranean basin`, () => {
      const lines = [...fixture.coastline, ...fixture.roads];
      expect(lines.length).toBeGreaterThan(0);

      const wrong: string[] = [];
      for (const line of lines) {
        // A one-point line draws nothing and still costs an array.
        if (line.length < 2) wrong.push(`a line has ${line.length} point(s)`);
        for (const point of line) {
          if (point.length !== 2) wrong.push(`a coordinate has ${point.length} numbers`);
          const [lon, lat] = point;
          if (!(lat >= BASIN.lat[0] && lat <= BASIN.lat[1])) wrong.push(`lat ${lat} is outside the basin`);
          if (!(lon >= BASIN.lon[0] && lon <= BASIN.lon[1])) wrong.push(`lon ${lon} is outside the basin`);
        }
      }
      expect(wrong.slice(0, 5)).toEqual([]);
    });

    test(`${id}: the geometry surrounds the centre it claims`, () => {
      // Catches the failure a basin check cannot: geometry that is real, inside
      // the Mediterranean, and a hundred kilometres from the place it is
      // labelled as. The bbox is the span times `BLEED`, so half the span plus
      // a margin is the furthest any point may legitimately sit.
      const [lon, lat] = fixture.center;
      const allowedKm = fixture.spanKm; // generous: the bbox half-span is 0.7x this
      const far: string[] = [];
      for (const line of [...fixture.coastline, ...fixture.roads]) {
        for (const [pLon, pLat] of line) {
          const dLatKm = (pLat - lat) * 111;
          const dLonKm = (pLon - lon) * 111 * Math.cos((lat * Math.PI) / 180);
          const km = Math.hypot(dLatKm, dLonKm);
          if (km > allowedKm) far.push(`${km.toFixed(1)} km from ${id}'s centre`);
        }
      }
      expect(far.slice(0, 3)).toEqual([]);
    });

    test(`${id}: the tolerance is one pixel of the span it is drawn at`, () => {
      // The knee of the size/quality curve, and the reason the files are small.
      // Drift either way is invisible in a render and obvious here.
      expect(fixture.toleranceM).toBe(Math.round((fixture.spanKm * 1000) / 330));
    });
  }

  test("only Troy carries roads, and it carries them because coastline alone is weak", () => {
    for (const id of geoIds) {
      expect({ id, roads: geo[id].roads.length > 0 }).toEqual({ id, roads: id === "troy" });
    }
  });

  test("the whole set stays in the same league as a single raster tile", () => {
    // The argument for vectors over tiles was a size argument as much as a
    // licence one. Stroke-only came to 11.6 KB gzipped for all five, against
    // ~16 KB for ONE raster tile; adding closed land for the fill took it to
    // about 16.5 KB, which is worth the bytes — a stroke does not say which
    // side is water, and that is the first thing a reader needs.
    //
    // The bound is 24 KB rather than the old 16, and the honest comparison is
    // not tile-for-tile anyway: a raster map needs a SET of tiles per theme,
    // which D25 measured at 400-700 KB across two asset sets. What this guards
    // is a blow-up — an unfiltered regeneration put Corfu alone at 17.7 KB by
    // keeping 467 rings, most of them outside the view or smaller than a pixel.
    const bytes = geoIds.reduce(
      (total, id) => total + gzipSync(new TextEncoder().encode(JSON.stringify(geo[id]))).length,
      0,
    );
    expect(bytes).toBeLessThan(24 * 1024);
  });
});

describe("the licence obligations are met", () => {
  test("the ODbL notice sits with the data it covers", () => {
    // In this directory, not the repo root: the rest of the tree is MIT and the
    // share-alike attaches to these files alone.
    const licence = join(GEO, "LICENSE");
    expect(existsSync(licence)).toBe(true);
    const text = readFileSync(licence, "utf8");
    expect(text).toContain("Open Database License");
    expect(text).toContain("OpenStreetMap contributors");
  });

  test("every scene drawing this geometry credits it", () => {
    // The obligation is on the scene, not on the component: `MapView` cannot
    // know where a caller's paths came from, so a scene that forgets the credit
    // renders a perfectly good map with no source. This is the check that makes
    // forgetting loud.
    const uncredited = mapScenes
      .filter((scene) => scene.paths.length > 0)
      .filter((scene) => {
        const usesGeo = geoIds.some((id) =>
          scene.paths.some((path) =>
            geo[id].coastline.some((line) => line[0]?.[0] === path.coords[0]?.[0] && line[0]?.[1] === path.coords[0]?.[1]),
          ),
        );
        return usesGeo && scene.attribution !== OSM_ATTRIBUTION;
      })
      .map((scene) => scene.title);
    expect(uncredited).toEqual([]);
  });

  test("the fixtures are not published, so the npm package stays pure MIT", () => {
    // The whole licence position rests on this: a Derivative Database carries
    // share-alike, and `packages/ui-kit` ships `src`, `dist` and the README.
    // Asserted rather than trusted, because `files` is one line in a manifest
    // and adding `fixtures` to it would relicense the tarball silently.
    const manifest = JSON.parse(readFileSync(join(KIT, "package.json"), "utf8")) as { files: string[] };
    expect(manifest.files).toEqual(["src", "dist", "README.md"]);
    expect(manifest.files).not.toContain("fixtures");
  });

  test("no geometry leaked into src/, where the MIT licence applies", () => {
    // `src` IS published. A coordinate array that migrates out of `fixtures/`
    // into a component default would put ODbL data in an MIT tarball, which is
    // the one mistake this whole arrangement exists to prevent.
    const mapView = readFileSync(join(KIT, "src", "blocks", "MapView.tsx"), "utf8");
    // The component's only hard-coded coordinate is its documented fallback
    // pin, which is a single point read from a Wikipedia geotag, not OSM
    // geometry. Anything resembling a polyline would be.
    const longArrays = mapView.match(/\[\s*\[\s*-?\d+\.\d+\s*,\s*-?\d+\.\d+\s*\]\s*,\s*\[/g) ?? [];
    expect(longArrays).toEqual([]);
  });
});
