/**
 * The OSM geometry: what it must be, and what it must not cost.
 *
 * `fixtures/geo/*.json` is generated by `tools/geo/generate.ts` and committed.
 * Generated data is exactly the kind that rots quietly — a regeneration with a
 * transposed bbox draws a confident map of the wrong sea, and a regeneration at
 * the wrong tolerance triples the bytes without changing a single rendered
 * pixel. Neither shows up in a typecheck, because the files are JSON and the
 * loader casts them once (`fixtures/geo/index.ts` says why).
 *
 * Three groups of assertion, and the third is the licence one.
 */

import { signedArea } from "@schlessera/brain-ui-sdk/server";
import { describe, expect, test } from "bun:test";
import { gzipSync } from "bun";
import { existsSync, readFileSync } from "fs";
import { join, resolve } from "path";

import { OSM_ATTRIBUTION, geo, geoIds, geoPaths, type GeoId } from "../fixtures/geo/index.js";
import { mapScenes } from "../fixtures/places.js";

const KIT = resolve(import.meta.dir, "..");
const GEO = join(KIT, "fixtures", "geo");

/** The same basin the rest of the world is checked against: a transposed
 * `[lat, lon]` pair lands outside it, which a spot check does not catch
 * because at these latitudes the two ranges overlap. */
const BASIN = { lat: [30, 46], lon: [-6, 37] } as const;

/**
 * The box a fixture was fetched for, which the file does not carry: the
 * generator derives it from `center` and `spanKm`, and so does this. The
 * arithmetic is `tools/geo/generate.ts`'s `bbox()` and the numbers are its
 * `BLEED_ACROSS` and `BLEED_DOWN` — the one place in this file that has to
 * agree with the generator rather than with the data.
 */
function envelope(id: GeoId): [number, number, number, number] {
  const { center, spanKm } = geo[id];
  const [lon, lat] = center;
  const dLat = spanKm / 2 / 111;
  const dLon = (spanKm * 1.5) / 2 / 111 / Math.cos((lat * Math.PI) / 180);
  return [lon - dLon, lat - dLat, lon + dLon, lat + dLat];
}

/** Is this point painted, under the even-odd rule `MapView` draws the rings
 * with? Ray casting, one crossing test per edge. */
function fills(rings: [number, number][][], [x, y]: [number, number]): boolean {
  let inside = false;
  for (const ring of rings) {
    for (let i = 0; i < ring.length - 1; i += 1) {
      const [ax, ay] = ring[i]!;
      const [bx, by] = ring[i + 1]!;
      if (ay > y !== by > y && x < ((bx - ax) * (y - ay)) / (by - ay) + ax) inside = !inside;
    }
  }
  return inside;
}

/**
 * A ring closed against the viewport, as opposed to one that closed on its own.
 *
 * Two or more of its vertices sit ON the box. Rings are never clipped, so an
 * island's coordinates land on the boundary only by a coincidence that four
 * decimal places make vanishingly unlikely; a closure's ends and corners are
 * the boundary by construction.
 */
function isClosedAgainstViewport(ring: [number, number][], box: [number, number, number, number]): boolean {
  // Four decimal places can move a coordinate by about 6 m, which at these
  // spans is a fifth of a pixel and well inside this.
  const near = (a: number, b: number) => Math.abs(a - b) < 1e-4;
  const on = ring.filter(([lon, lat]) => near(lon, box[0]) || near(lon, box[2]) || near(lat, box[1]) || near(lat, box[3]));
  return on.length >= 2;
}

/**
 * How close to an edge "which side of it is this point on" stops having an
 * answer: the four decimal places every coordinate is rounded to, about 10 m.
 */
const EDGE = 1e-4;

/** Is this point within `EDGE` of any edge of these rings, in degrees? */
function onAnEdge(rings: [number, number][][], [x, y]: [number, number]): boolean {
  for (const ring of rings) {
    for (let i = 0; i < ring.length - 1; i += 1) {
      const [ax, ay] = ring[i]!;
      const [bx, by] = ring[i + 1]!;
      const dx = bx - ax;
      const dy = by - ay;
      const t = Math.max(0, Math.min(1, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy || 1)));
      if (Math.hypot(x - ax - t * dx, y - ay - t * dy) < EDGE) return true;
    }
  }
  return false;
}

/**
 * Which side of the fill the road network came out on, as the witness gate
 * reports it.
 *
 * Strictly inside, not merely within — of the box AND of the fill. A road is
 * clipped to the same box the closure is drawn against, so its end vertices sit
 * exactly ON the fill's own edge, and "which side of this edge is that point
 * on" has no answer there: the strait has three of them on its eastern
 * boundary, and counting them as sea made a fill that contains every road read
 * as 99.4%. The shore is the same edge by another name. A road that ends at a
 * harbour, or runs along a quay, shares its vertex with the coastline or sits
 * within a rounding step of it, and that is Ithaca's one, Troy's one and
 * Vathy's five (#133, maintainer ruling). A vertex further out than `EDGE` is
 * in the sea, and still counts against the fill.
 */
function witnessReading(
  roads: [number, number][][],
  land: [number, number][][],
  box: [number, number, number, number],
): string {
  const witnesses = roads
    .flat()
    .filter(
      ([lon, lat]) => lon > box[0] + EDGE && lon < box[2] - EDGE && lat > box[1] + EDGE && lat < box[3] - EDGE,
    )
    .filter((point) => !onAnEdge(land, point));
  if (witnesses.length < 20) return "too few witnesses";
  const onLand = witnesses.filter((point) => fills(land, point)).length;
  return `${((onLand / witnesses.length) * 100).toFixed(1)}% of ${witnesses.length} road vertices are on land`;
}

describe("the geometry is geometry", () => {
  test("every location loaded", () => {
    // A guard on the guard: an empty set would pass every loop below.
    expect(geoIds).toEqual(["ithaca", "gozo", "corfu", "messina", "troy", "vathy"]);
  });

  for (const id of geoIds) {
    const fixture = geo[id];

    test(`${id}: every coordinate is a pair inside the Mediterranean basin`, () => {
      const lines = [...fixture.coastline, ...fixture.roads, ...(fixture.streets ?? []), ...(fixture.land ?? [])];
      expect(lines.length).toBeGreaterThan(0);

      const wrong: string[] = [];
      for (const line of lines) {
        // A one-point line draws nothing and still costs an array.
        if (line.length < 2) wrong.push(`a line has ${line.length} point(s)`);
        for (const point of line) {
          if (point.length !== 2) wrong.push(`a coordinate has ${point.length} numbers`);
          const [lon, lat] = point;
          if (!(lat >= BASIN.lat[0] && lat <= BASIN.lat[1])) wrong.push(`lat ${lat} is outside the basin`);
          if (!(lon >= BASIN.lon[0] && lon <= BASIN.lon[1])) wrong.push(`lon ${lon} is outside the basin`);
        }
      }
      expect(wrong.slice(0, 5)).toEqual([]);
    });

    test(`${id}: the geometry surrounds the centre it claims`, () => {
      // Catches the failure a basin check cannot: geometry that is real, inside
      // the Mediterranean, and a hundred kilometres from the place it is
      // labelled as. The generator fetches an envelope 1.5 times the scene's
      // width across and 1.0 times it down — every frame a bounded card can
      // draw, and nothing past it — so a stroke can reach 0.75 spans east or
      // west of the centre and 0.5 spans north or south. A radial one-span
      // bound wrongly rejects the bleed and the box's corners; the old square
      // 1.2-span bound would let a regeneration with the symmetric bleed back
      // in unnoticed, and that bleed is what tripled the bytes.
      // Four-decimal rounding can move a boundary coordinate by about 6 m.
      // Land rings stay whole for SVG clipping, so only strokes are bounded.
      const [lon, lat] = fixture.center;
      const acrossKm = fixture.spanKm * 0.75 + 0.01;
      const downKm = fixture.spanKm * 0.5 + 0.01;
      const far: string[] = [];
      const strokes = [...fixture.coastline, ...fixture.roads, ...(fixture.streets ?? [])];
      expect(strokes.length, `${id}: surrounding strokes are nonempty`).toBeGreaterThan(0);
      for (const line of strokes) {
        for (const [pLon, pLat] of line) {
          const dLatKm = (pLat - lat) * 111;
          const dLonKm = (pLon - lon) * 111 * Math.cos((lat * Math.PI) / 180);
          if (Math.abs(dLatKm) > downKm || Math.abs(dLonKm) > acrossKm) {
            far.push(`${dLonKm.toFixed(2)},${dLatKm.toFixed(2)} km from ${id}'s centre`);
          }
        }
      }
      expect(far.slice(0, 3)).toEqual([]);
    });

    test(`${id}: the tolerance is one pixel of the span it is drawn at`, () => {
      // The knee of the size/quality curve, and the reason the files are small.
      // Drift either way is invisible in a render and obvious here.
      expect(fixture.toleranceM).toBe(Math.round((fixture.spanKm * 1000) / 330));
    });
  }

  test("detail tiers keep their promised layers and reach the rendered paths", () => {
    for (const id of geoIds) {
      const fixture = geo[id];
      const streets = fixture.streets ?? [];
      // Legacy files have no detail metadata; regenerated files must be
      // complete and use the scene's scale (Troy deliberately forces roads).
      if (fixture.detail) {
        const expected = id === "troy" ? "roads"
          : fixture.toleranceM <= 8 ? "streets"
          : fixture.toleranceM <= 40 ? "roads" : "coast";
        expect({ id, detail: fixture.detail, partial: fixture.partial }).toEqual({ id, detail: expected, partial: false });
        if (expected !== "coast") expect(fixture.roads.length).toBeGreaterThan(0);
        if (expected === "streets") expect(streets.length).toBeGreaterThan(0);
        else expect(streets).toHaveLength(0);
      }
      const paths = geoPaths(id);
      expect(paths.map((path) => path.coords)).toEqual([...fixture.coastline, ...fixture.roads, ...streets]);
      for (const path of paths.slice(fixture.coastline.length + fixture.roads.length)) {
        expect(path.width).toBeLessThan(0.6);
      }
    }
  });

  test("every outer land ring is wound counterclockwise, which is what land-on-the-left means", () => {
    // The fact the viewport closure rests on: OSM winds a coastline so that
    // land is on its left, which makes an island's ring counterclockwise.
    // Measured at 486 of 486 rings across Gozo, Corfu and Ithaca before the
    // closure was built (`docs/decisions/design-feedback.md`); asserted here so
    // a regeneration that brought data wound the other way could not land
    // quietly, because the closure would then fill the sea.
    //
    // A ring INSIDE another is an inland water body and is wound the other way
    // on purpose — that is what makes it a hole under the even-odd rule. None
    // of these six has one today, which is a fact about the data rather than a
    // rule, so the exception is written down rather than assumed away.
    const backwards: string[] = [];
    for (const id of geoIds) {
      const rings = geo[id].land ?? [];
      expect(rings.length, `${id}: land rings are nonempty`).toBeGreaterThan(0);
      for (const ring of rings) {
        const nested = rings.some((other) => other !== ring && fills([other], ring[0]!));
        if (!nested && signedArea(ring) <= 0) backwards.push(`${id}: a ring of ${ring.length} points`);
      }
    }
    expect(backwards).toEqual([]);
  });

  test("where a shore was closed against the viewport, the roads came out on the land side", () => {
    // The check that a predicate on the vertices cannot make: a closure wound
    // the wrong way round is the exact complement of the right one — the sea,
    // filled confidently — and its ring list looks just as plausible. A road is
    // on land by definition, so asking which side of the fill the road network
    // is on is asking whether the fill is land.
    //
    // Only fixtures that actually carry a closure are asked. The rest predate
    // it and still draw their mainland as a stroke, which is not wrong, only
    // older; this starts holding them to it the moment they are regenerated.
    const measured: string[] = [];
    for (const id of geoIds) {
      const fixture = geo[id];
      const box = envelope(id);
      if (!(fixture.land ?? []).some((ring) => isClosedAgainstViewport(ring, box))) continue;
      measured.push(`${id}: ${witnessReading([...fixture.roads, ...(fixture.streets ?? [])], fixture.land, box)}`);
    }
    // The measurement is in the expectation rather than behind a threshold: a
    // fixture that stops carrying a closure, one whose closure inverted, and
    // one that merely drifted are three different failures and this says which.
    //
    // Gozo and Corfu fetch no roads, so "too few witnesses" is the honest
    // answer for them rather than an omission.
    expect(measured).toEqual([
      "ithaca: 100.0% of 110 road vertices are on land",
      "gozo: too few witnesses",
      "corfu: too few witnesses",
      "messina: 100.0% of 508 road vertices are on land",
      "troy: 100.0% of 310 road vertices are on land",
      "vathy: 100.0% of 481 road vertices are on land",
    ]);
  });

  test("the shore exclusion is a rounding step wide, and a road in the sea past it still counts", () => {
    // The guard on the rule above. A square island in a larger box, a road
    // network well inside it, and one vertex just off its eastern shore: a
    // loosened `EDGE` would swallow that vertex, and with it the ability to see
    // a fill that stops short of the roads.
    const land: [number, number][][] = [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]];
    const box: [number, number, number, number] = [-1, -1, 2, 2];
    const inland: [number, number][] = Array.from({ length: 25 }, (_, i) => [0.1 + i * 0.03, 0.5]);
    expect(witnessReading([inland], land, box)).toBe("100.0% of 25 road vertices are on land");
    // ON the shore, a fifth of a rounding step out: no answer, not counted.
    expect(witnessReading([[...inland, [1.00002, 0.5]]], land, box)).toBe("100.0% of 25 road vertices are on land");
    // Two rounding steps out — about 20 m of sea — is a road off the fill.
    expect(witnessReading([[...inland, [1.0002, 0.5]]], land, box)).toBe("96.2% of 26 road vertices are on land");
  });

  test("the whole set stays in the same league as a single raster tile", () => {
    // The argument for vectors over tiles was a size argument as much as a
    // licence one. Stroke-only came to 11.6 KB gzipped for all five, against
    // ~16 KB for ONE raster tile; adding closed land for the fill took it to
    // about 16.5 KB, which is worth the bytes — a stroke does not say which
    // side is water, and that is the first thing a reader needs.
    //
    // The bound was 24 KB for five locations; Vathy, the street-tier demo,
    // is a sixth (4.4 KB and 159 streets under the old square bleed, 2.3 KB
    // and 118 streets under the 1.5 x 1.0 envelope), so it is 28 KB. The honest
    // comparison is not tile-for-tile anyway: a raster map needs a SET of
    // tiles per theme, which D25 measured at 400-700 KB across two asset
    // sets. What this guards is a blow-up — an unfiltered regeneration put
    // Corfu alone at 17.7 KB by keeping 467 rings, most of them outside the
    // view or smaller than a pixel, and a 2026-09-19 regeneration of Troy and
    // Messina through the current road tier came back at 11.5 and 7.9 KB
    // (three and ten times their committed size) and was not kept. The
    // envelope was the lever, not the road filter: with 1.5 x 1.0 (sixth
    // pass, S10) all six regenerate to 24.8 KB together, Messina with its
    // full road tier at 2.8 KB. Closing every mainland shore against that
    // envelope (#133) took the six from 24.3 to 26.0 KB, 1.1 KB of it Corfu's.
    const bytes = geoIds.reduce(
      (total, id) => total + gzipSync(new TextEncoder().encode(JSON.stringify(geo[id]))).length,
      0,
    );
    expect(bytes).toBeLessThan(28 * 1024);
  });

  test("a street layer is drawn after roads, on a fixture that has none of its own", () => {
    const fixture = geo.ithaca;
    const previous = fixture.streets;
    const street: [number, number][] = [[20.7202, 38.3647], [20.721, 38.365]];
    try {
      fixture.streets = [street];
      const paths = geoPaths("ithaca");
      expect(paths).toHaveLength(fixture.coastline.length + fixture.roads.length + 1);
      expect(paths.at(-1)?.coords).toBe(street);
      expect(paths.at(-1)?.width).toBeLessThan(0.6);
    } finally {
      if (previous === undefined) delete fixture.streets;
      else fixture.streets = previous;
    }
  });
});

describe("the licence obligations are met", () => {
  test("the ODbL notice sits with the data it covers", () => {
    // In this directory, not the repo root: the rest of the tree is MIT and the
    // share-alike attaches to these files alone.
    const licence = join(GEO, "LICENSE");
    expect(existsSync(licence)).toBe(true);
    const text = readFileSync(licence, "utf8");
    expect(text).toContain("Open Database License");
    expect(text).toContain("OpenStreetMap contributors");
  });

  test("every scene drawing this geometry credits it", () => {
    // The obligation is on the scene, not on the component: `MapView` cannot
    // know where a caller's paths came from, so a scene that forgets the credit
    // renders a perfectly good map with no source. This is the check that makes
    // forgetting loud.
    const uncredited = mapScenes
      .filter((scene) => scene.paths.length > 0)
      .filter((scene) => {
        const usesGeo = geoIds.some((id) =>
          scene.paths.some((path) =>
            geo[id].coastline.some((line) => line[0]?.[0] === path.coords[0]?.[0] && line[0]?.[1] === path.coords[0]?.[1]),
          ),
        );
        return usesGeo && scene.attribution !== OSM_ATTRIBUTION;
      })
      .map((scene) => scene.title);
    expect(uncredited).toEqual([]);
  });

  test("the fixtures are not published, so the npm package stays pure MIT", () => {
    // The whole licence position rests on this: a Derivative Database carries
    // share-alike, and `packages/ui-kit` ships `src`, `dist`, the logo files in
    // `assets` (#1424, held to the accepted masters by brand-assets.test.ts)
    // and the README. Asserted rather than trusted, because `files` is one line
    // in a manifest and adding `fixtures` to it would relicense the tarball
    // silently.
    const manifest = JSON.parse(readFileSync(join(KIT, "package.json"), "utf8")) as { files: string[] };
    expect(manifest.files).toEqual(["src", "dist", "assets", "README.md"]);
    expect(manifest.files).not.toContain("fixtures");
  });

  test("no geometry leaked into src/, where the MIT licence applies", () => {
    // `src` IS published. A coordinate array that migrates out of `fixtures/`
    // into a component default would put ODbL data in an MIT tarball, which is
    // the one mistake this whole arrangement exists to prevent.
    const mapView = readFileSync(join(KIT, "src", "blocks", "MapView.tsx"), "utf8");
    // The component's only hard-coded coordinate is its documented fallback
    // pin, which is a single point read from a Wikipedia geotag, not OSM
    // geometry. Anything resembling a polyline would be.
    const longArrays = mapView.match(/\[\s*\[\s*-?\d+\.\d+\s*,\s*-?\d+\.\d+\s*\]\s*,\s*\[/g) ?? [];
    expect(longArrays).toEqual([]);
  });
});
