// Real coastline, as `MapView` paths.
//
// The geometry is OpenStreetMap's, simplified to one pixel of the render it is
// drawn at. **It is ODbL, unlike everything else in this repository** — see
// `LICENSE` in this directory before copying a file out of it, and note that
// the rendered map is a Produced Work and carries no such obligation.
//
// `tools/geo/generate.ts` regenerates these files. Run it by hand; Overpass is
// not for a test suite.
//
// ## Why coastline at all
//
// The graticule and scale bar alone make an accurate locator and an
// unrecognisable picture — a radar view. D25 measured the alternatives: raster
// tiles are out (a browser component cannot identify itself to a tile server,
// every keyless provider forbids commercial use, and a visual-regression suite
// panning a map is exactly what OSM's policy calls bulk downloading), and
// Natural Earth, which is public domain and would have been the easy answer, is
// five to ten times too coarse at these spans.
//
// ## Tone is the caller's, and quiet is the point
//
// Coastline is CONTEXT, not content: it says where, and the pins and the route
// say what. It goes in at `neutral` and hairline width so a 2px amber route
// still reads as the subject. A scene that draws its coastline as loudly as its
// route has buried its own argument.

import type { MapLand, MapPath } from "../../src/blocks/MapView.js";

import corfu from "./corfu.json" with { type: "json" };
import gozo from "./gozo.json" with { type: "json" };
import ithaca from "./ithaca.json" with { type: "json" };
import messina from "./messina.json" with { type: "json" };
import troy from "./troy.json" with { type: "json" };
import vathy from "./vathy.json" with { type: "json" };

/** One generated file, as `tools/geo/generate.ts` writes it. */
export interface GeoFixture {
  id: string;
  label: string;
  /** `[lon, lat]`, matching `MapPath["coords"]`. */
  center: [number, number];
  spanKm: number;
  /** The simplification tolerance in metres — one pixel of the target render. */
  toleranceM: number;
  attribution: string;
  coastline: [number, number][][];
  /** Major roads at town scale, or explicitly requested for legibility. */
  roads: [number, number][][];
  /** Older fixtures predate detail tiers; absence means no streets. */
  streets?: [number, number][][];
  detail?: "coast" | "roads" | "streets";
  partial?: boolean;
  /**
   * Closed rings of land, for the fill. Two kinds, drawn as one path under the
   * even-odd rule: an island's coastline, which stitches head-to-tail into a
   * loop, and a mainland shore closed against the fetch envelope on the land
   * side. Files generated before the second existed carry only the first, and
   * draw their mainland as a stroke — which is not wrong, only older.
   */
  land: [number, number][][];
}

/**
 * A JSON import widens every tuple: `[lon, lat]` arrives as `number[]`, so
 * `center` and every coordinate lose the pair-ness `MapPath` requires. There is
 * no way to recover that from the type system — the file is data — so it is one
 * documented cast, and `tests/geo-fixtures.test.ts` checks the shape for real:
 * two numbers per coordinate, every one inside the Mediterranean basin, every
 * line at least two points long. An unchecked cast paired with an actual
 * assertion is honest; an unchecked cast on its own is a hope.
 */
function adopt(raw: unknown): GeoFixture {
  return raw as GeoFixture;
}

export const geo = {
  ithaca: adopt(ithaca),
  gozo: adopt(gozo),
  corfu: adopt(corfu),
  messina: adopt(messina),
  troy: adopt(troy),
  vathy: adopt(vathy),
} as const;

export type GeoId = keyof typeof geo;

export const geoIds = Object.keys(geo) as GeoId[];

/** The line every scene drawing this geometry has to carry. */
export const OSM_ATTRIBUTION = "© OpenStreetMap contributors";

/**
 * A location's geometry as `MapView` paths: coastline first, then roads, so a
 * road drawn over its own shoreline reads as a road.
 *
 * Each finer tier comes in a step quieter than the last, so streets locate a
 * block without competing with the coast or the caller's route.
 */
export function geoPaths(id: GeoId): MapPath[] {
  const fixture = geo[id];
  return [
    ...fixture.coastline.map((coords) => ({ coords, tone: "neutral" as const, width: 1 })),
    ...fixture.roads.map((coords) => ({ coords, tone: "neutral" as const, width: 0.6 })),
    ...(fixture.streets ?? []).map((coords) => ({ coords, tone: "neutral" as const, width: 0.35 })),
  ];
}

/**
 * A location's land, for `MapView`'s `land` prop.
 *
 * Still empty for a file generated before viewport closure existed, and that is
 * the honest answer rather than a failure: the map then draws its coastline as
 * a stroke, which is what it did before fill existed.
 */
export function geoLand(id: GeoId): MapLand | undefined {
  // `?? []` is not defensive padding: these files are regenerated by hand, one
  // location at a time, so a half-updated set is a normal intermediate state.
  // A file written before `land` existed should mean "no fill here", which is
  // also the honest answer for a mainland bbox — not a crash that takes every
  // story on the page with it.
  const rings = geo[id].land ?? [];
  return rings.length ? { rings } : undefined;
}
