/**
 * Markdown is the source of truth, so replacing a document must never leave
 * it half-written (#1355). Every write of a user document goes through one
 * writer, `writeFileSafely`: the bytes go to a temporary sibling first and are
 * renamed over the document only once complete, keeping its mode.
 *
 * The failure here is a real one. The MCP server runs under a file-size limit
 * (RLIMIT_FSIZE, with SIGXFSZ ignored), so a write past the limit fails with
 * EFBIG in the kernel, as a full disk fails a write with ENOSPC. A plain
 * `writeFileSync` truncates the document before it fails.
 */

import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { chmodSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "fs";
import { join, relative } from "path";
import { Glob } from "bun";

import { BRAIN_BIN, cleanup, keylessEnv, makeTempBrain, runCli } from "./cli-harness";

const SOURCE = [
  "---",
  "title: Ithaca supply ledger",
  "type: note",
  "status: active",
  "created: 2026-07-01",
  "updated: 2026-07-01",
  "---",
  "",
  "Forty jars of oil remain for the voyage home.",
  "",
].join("\n");

/** 512-byte blocks in `sh`'s `ulimit -f`: at most 32 KiB, far below the append below. */
const SIZE_LIMIT_BLOCKS = 64;
const OVERSIZED_APPEND = "The ledger repeats. ".repeat(10_000);

describe("brain_update", () => {
  let root: string;
  // `limited` runs under the file-size limit; `client` does not, since the
  // reindex after a successful write needs to write brain.db.
  let limited: Client;
  let client: Client;

  beforeAll(async () => {
    root = makeTempBrain({ empty: true });
    writeFileSync(join(root, "brain.config.ts"), "export default {};\n");
    mkdirSync(join(root, "notes"), { recursive: true });
    writeFileSync(join(root, "notes/ledger.md"), SOURCE);
    chmodSync(join(root, "notes/ledger.md"), 0o640);
    expect((await runCli(root, ["index", "--json"])).code).toBe(0);
    limited = new Client({ name: "document-writes-test", version: "1.0.0" });
    await limited.connect(new StdioClientTransport({
      command: "/bin/sh",
      args: ["-c", `trap '' XFSZ; ulimit -f ${SIZE_LIMIT_BLOCKS}; exec "$0" "$1" mcp`, process.execPath, BRAIN_BIN],
      env: keylessEnv(root),
    }));
    client = new Client({ name: "document-writes-test", version: "1.0.0" });
    await client.connect(new StdioClientTransport({ command: process.execPath, args: [BRAIN_BIN, "mcp"], env: keylessEnv(root) }));
  });

  afterAll(async () => {
    await limited?.close();
    await client?.close();
    cleanup(root);
  });

  test("a write that fails part-way leaves the document as it was", async () => {
    // The appended section alone is several times the limit: a write of it fails.
    expect(OVERSIZED_APPEND.length).toBeGreaterThan(SIZE_LIMIT_BLOCKS * 1024 * 2);
    const res = await limited.callTool({
      name: "brain_update",
      arguments: { path: "notes/ledger.md", append_content: OVERSIZED_APPEND },
    });
    expect(res.isError).toBe(true);
    expect(JSON.stringify(res.content)).toContain("EFBIG");
    expect(readFileSync(join(root, "notes/ledger.md"), "utf8")).toBe(SOURCE);
    // The failed temporary sibling is gone too.
    expect(readdirSync(join(root, "notes"))).toEqual(["ledger.md"]);
  });

  test("a write that succeeds replaces the document and keeps its mode", async () => {
    writeFileSync(join(root, "notes/ledger.md"), SOURCE);
    expect(statSync(join(root, "notes/ledger.md")).mode & 0o7777).toBe(0o640);
    const res = await client.callTool({
      name: "brain_update",
      arguments: { path: "notes/ledger.md", summary: "What is left for the crossing" },
    });
    expect(res.isError, JSON.stringify(res.content)).toBeFalsy();
    const after = readFileSync(join(root, "notes/ledger.md"), "utf8");
    expect(after).toContain("What is left for the crossing");
    expect(after).toContain("Forty jars of oil remain");
    expect(statSync(join(root, "notes/ledger.md")).mode & 0o7777).toBe(0o640);
    expect(readdirSync(join(root, "notes"))).toEqual(["ledger.md"]);
  });
});

/**
 * Files in core's source that may still call `writeFileSync`, and why none of
 * their writes replaces a user document. Anything else writes through
 * `writeFileSafely` (`packages/core/src/lib/safe-path.ts`).
 */
const PLAIN_WRITERS: Record<string, string> = {
  "cli/commands/init.ts": "scaffolds a new brain: each file is written only when absent",
  "lib/indexer/caches.ts": "derived caches, regenerated by `brain index --force`",
  "lib/skills/emitters/codex.ts": "agent instruction files, not brain documents",
  "lib/skills/emitters/gemini.ts": "agent instruction files, not brain documents",
  "lib/skills/emitters/index-block.ts": "agent instruction files, not brain documents",
  "lib/sync/artifacts.ts": ".gitignore, restored by its own undo",
  "lib/sync/merge-state.ts": "markers inside .git",
  "lib/sync/pull.ts": "derived caches set aside around a merge",
  "testing/agent-runners.ts": "test support, never run against a brain",
  "testing/skill-emitters.ts": "test support, never run against a brain",
};

test("no core source outside the allowlist calls writeFileSync", () => {
  const src = join(import.meta.dir, "../src");
  const offenders: string[] = [];
  const seen = new Set<string>();
  for (const file of new Glob("**/*.ts").scanSync({ cwd: src })) {
    const text = readFileSync(join(src, file), "utf8");
    if (!/\bwriteFileSync\s*\(/.test(text)) continue;
    const rel = relative(src, join(src, file)).split("\\").join("/");
    seen.add(rel);
    if (!(rel in PLAIN_WRITERS)) offenders.push(rel);
  }
  expect(offenders).toEqual([]);
  // An entry whose file no longer writes is stale; drop it.
  expect(Object.keys(PLAIN_WRITERS).filter((rel) => !seen.has(rel))).toEqual([]);
});
