import assert from 'node:assert/strict';
import { resolve } from 'node:path';
import { createHash } from 'node:crypto';
import { sourceInputHash, snapshotName } from './publication-source.ts';

const root = process.argv[2] ? resolve(process.argv[2]) : resolve(import.meta.dir, '../..');
const snapshot = await Bun.file(resolve(root, snapshotName)).json();
const file = Bun.file(resolve(root, 'website/dist/build-manifest.json'));
const manifest = await file.json();
assert.equal(snapshot.sourceDirty, false, 'Website checkout was dirty');
assert.equal(await sourceInputHash(root), snapshot.inputHash, 'Publication source inputs changed during the build');
if (snapshot.editorialRoot) assert.equal(await sourceInputHash(snapshot.editorialRoot), snapshot.editorialInputHash, 'Canonical editorial inputs changed during the build');
assert.equal(manifest.sourceSha, process.env.WEBSITE_SOURCE_SHA, 'Website source does not match the selected commit');
assert.equal(manifest.dirty, false, 'Artifact has changed source inputs');
assert.equal(manifest.base, '/brain-kit/', 'Wrong Pages base');
assert.equal(manifest.brainKit.sourceSha, process.env.EXPECTED_BRAIN_KIT_SHA, 'Demo does not match the selected product commit');
assert.equal(manifest.brainKit.tag || '', process.env.EXPECTED_BRAIN_KIT_TAG || '', 'Demo does not match the selected release tag');
assert.deepEqual(manifest.brainKit, snapshot.brainKit, 'Product provenance changed');
const shares = await Bun.file(resolve(root, 'website/dist/assets/shares/provenance.json')).json();
assert.equal(shares.sourceSha, manifest.sourceSha, 'Exports belong to another website commit');
assert.equal(shares.recipeHash, manifest.exportRecipeHash, 'Exports were not regenerated for this product');
assert.deepEqual(shares.brainKit, manifest.brainKit, 'Exports belong to another product build');
const previews = await Bun.file(resolve(root, 'website/dist/assets/previews/provenance.json')).json();
assert.equal(previews.sourceSha, manifest.sourceSha, 'Fallback screenshots belong to another website commit');
assert.equal(previews.recipeHash, manifest.exportRecipeHash, 'Fallback screenshots were not regenerated');
assert.deepEqual(previews.brainKit, manifest.brainKit, 'Fallback screenshots belong to another product build');
assert.equal(Object.keys(previews.assets).length, 4, 'Missing fallback screenshots');
for (const [name, receipt] of Object.entries(previews.assets) as [string, { sha256: string }][]) assert.equal(manifest.files[`assets/previews/${name}`], receipt.sha256, 'Fallback screenshot does not match its provenance');
const hash = createHash('sha256').update(new Uint8Array(await file.arrayBuffer())).digest('hex');
const receipt = `Website: ${manifest.sourceSha}\nBrain-kit: ${manifest.brainKit.version} (${manifest.brainKit.mode}), ${manifest.brainKit.sourceSha}\nRelease tag: ${manifest.brainKit.tag || 'main workspace'}\nManifest SHA-256: ${hash}\nFiles: ${Object.keys(manifest.files).length}\n`;
await Bun.write(resolve(root, 'website/test-results/publication.txt'), receipt);
if (process.env.GITHUB_STEP_SUMMARY) await Bun.write(process.env.GITHUB_STEP_SUMMARY, (await Bun.file(process.env.GITHUB_STEP_SUMMARY).text()) + `### Verified website artifact\n\n\`\`\`text\n${receipt}\`\`\`\n`);
console.log(receipt);
