// Writes a checked-in report of every package's public API surface —
// the exported names per export subpath, split into runtime values and
// type-only exports.
//
// Why: core's `.` export grew to 136 lines of re-exports one reasonable PR at
// a time, because the surface had no artifact a reviewer could see change. The
// reports under api-report/ are that artifact: any surface change shows up as
// a diff in review, and tests/api-surface.test.ts fails when the sources and
// the checked-in reports disagree.
//
// The surface is derived STATICALLY with the TypeScript compiler API — the
// packages are never imported. ui-react is browser code and core/ui-server
// pull `bun:sqlite`; importing them here would tie this report to a runtime.
//
// Regenerate: bun run api-report

import { existsSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "fs";
import { join, relative, resolve } from "path";
import ts from "typescript";

const ROOT = resolve(import.meta.dir, "..");
const PACKAGES_DIR = join(ROOT, "packages");
const REPORT_DIR = join(ROOT, "api-report");

interface Manifest {
  name: string;
  private?: boolean;
  exports?: Record<string, string | Record<string, string>>;
}

interface Entry {
  subpath: string;
  target: string; // as written in package.json
  file: string | null; // absolute path when it is TypeScript source, else null
}

function publishablePackages(): { dir: string; manifest: Manifest }[] {
  return readdirSync(PACKAGES_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => ({
      dir: e.name,
      manifest: JSON.parse(
        readFileSync(join(PACKAGES_DIR, e.name, "package.json"), "utf8")
      ) as Manifest,
    }))
    .filter((p) => !p.manifest.private);
}

/** The source file behind one export subpath — the `bun` condition, which is
 * the TypeScript entry all other conditions are built from. */
function entriesOf(dir: string, manifest: Manifest): Entry[] {
  const entries: Entry[] = [];
  for (const [subpath, value] of Object.entries(manifest.exports ?? {}).sort()) {
    const target = typeof value === "string" ? value : value.bun ?? value.default;
    const isSource = /\.(ts|tsx)$/.test(target ?? "");
    entries.push({
      subpath,
      target,
      file: isSource ? join(PACKAGES_DIR, dir, target) : null,
    });
  }
  return entries;
}

function compilerOptions(): ts.CompilerOptions {
  const config = ts.readConfigFile(join(ROOT, "tsconfig.json"), ts.sys.readFile);
  if (config.error) throw new Error("could not read tsconfig.json");
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, ROOT);
  return { ...parsed.options, noEmit: true };
}

/** `export type { X }` / `export { type X }` strips the value even when X's
 * declaration has one. */
function isTypeOnlyExport(symbol: ts.Symbol): boolean {
  return (symbol.declarations ?? []).some(
    (decl) =>
      ts.isExportSpecifier(decl) && (decl.isTypeOnly || decl.parent.parent.isTypeOnly)
  );
}

/** `value` or `type` for one export symbol, resolving alias chains. */
function classify(checker: ts.TypeChecker, symbol: ts.Symbol): "value" | "type" {
  if (isTypeOnlyExport(symbol)) return "type";
  let resolved = symbol;
  if (resolved.flags & ts.SymbolFlags.Alias) {
    try {
      resolved = checker.getAliasedSymbol(resolved);
    } catch {
      return "value"; // unresolved external; assume the stronger claim
    }
  }
  return resolved.flags & ts.SymbolFlags.Value ? "value" : "type";
}

/** Builds every package's report in one pass (one program, one lib parse). */
export function generateReports(): Map<string, string> {
  const packages = publishablePackages();
  const allEntries = new Map(packages.map((p) => [p.dir, entriesOf(p.dir, p.manifest)]));

  const rootNames = [...allEntries.values()]
    .flat()
    .map((e) => e.file)
    .filter((f): f is string => f !== null);
  const program = ts.createProgram(rootNames, compilerOptions());
  const checker = program.getTypeChecker();

  const reports = new Map<string, string>();
  for (const { dir, manifest } of packages) {
    const lines: string[] = [
      `# ${manifest.name} — public API surface (packages/${dir})`,
      "# Generated by \`bun run api-report\`; verified by tests/api-surface.test.ts.",
      "# A diff in this file is a public-surface change — review it as one.",
      "# Names marked \`type\` are type-only exports; the rest are runtime values.",
    ];
    for (const entry of allEntries.get(dir)!) {
      lines.push("", `export "${entry.subpath}" (${entry.target})${entry.file ? "" : " [asset]"}`);
      if (!entry.file) continue;
      const source = program.getSourceFile(entry.file);
      if (!source) throw new Error(`program did not load ${entry.file}`);
      const moduleSymbol = checker.getSymbolAtLocation(source);
      if (!moduleSymbol) throw new Error(`${entry.file} has no module symbol (no exports?)`);
      const names = checker
        .getExportsOfModule(moduleSymbol)
        .map((s) => ({ name: s.getName(), kind: classify(checker, s) }))
        .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
      for (const { name, kind } of names) {
        lines.push(kind === "type" ? `  type ${name}` : `  ${name}`);
      }
    }
    reports.set(`${dir}.txt`, lines.join("\n") + "\n");
  }
  return reports;
}

if (import.meta.main) {
  const reports = generateReports();
  mkdirSync(REPORT_DIR, { recursive: true });
  for (const [file, content] of reports) {
    writeFileSync(join(REPORT_DIR, file), content);
    console.log(`wrote ${relative(ROOT, join(REPORT_DIR, file))}`);
  }
  // A report whose package is gone would sit around asserting a surface that
  // no longer exists; sweep it.
  if (existsSync(REPORT_DIR)) {
    for (const file of readdirSync(REPORT_DIR)) {
      if (file.endsWith(".txt") && !reports.has(file)) {
        unlinkSync(join(REPORT_DIR, file));
        console.log(`removed stale ${relative(ROOT, join(REPORT_DIR, file))}`);
      }
    }
  }
}
