/**
 * Fork pull request CI adapters (#988).
 *
 * Depot CI runs this repo's CI and contract gates for same-repository pull
 * requests and pushes to main, but it does not receive pull requests from
 * forks. GitHub Actions runs the same gates for those, from adapters this
 * script derives from the Depot definitions. The Depot files stay the only
 * place a gate is written; the adapters are regenerated, never edited.
 *
 * An adapter differs from its source in exactly these ways, and in no other:
 *
 * - routing: the workflow triggers on `pull_request` only (a source `push`
 *   trigger is dropped), each job runs only when the PR's head repository is
 *   not the base repository (`FORK_ROUTE`), and each job is named
 *   `fork / <job>` so its check can never stand in for a Depot `CI / <job>`
 *   check of the same job. The workflow name gains ` (fork fallback)`.
 * - runner mapping: each Depot runner label becomes the GitHub-hosted label in
 *   `RUNNER_MAP`. An unmapped label refuses generation.
 * - fork-context credential handling: every `actions/checkout` step gains
 *   `persist-credentials: false`, so the read-only token is not left in the
 *   checkout's git config for the fork's code to read.
 *
 * Each Depot job must carry `if: <DEPOT_ROUTE>`, the complement of
 * `FORK_ROUTE`: whatever a provider is given, exactly one of them runs a job.
 * The transform is textual, so the source's comments and layout survive into
 * the adapter. Any shape it does not recognise is refused rather than guessed.
 *
 *   bun scripts/fork-ci-adapters.ts --check   # fail if an adapter is stale
 *   bun scripts/fork-ci-adapters.ts --write   # regenerate the adapters
 *
 * `tests/fork-ci-adapters.test.ts` checks the result independently, by parsing
 * both files and comparing every job, step, matrix and setting.
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";

const ROOT = resolve(import.meta.dir, "..");

/** Depot runs a job for a push, a local `api` run or a same-repository PR. */
export const DEPOT_ROUTE =
  "github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository";

/** GitHub Actions runs a job only for a pull request from another repository. */
export const FORK_ROUTE =
  "github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository";

/** Depot runner label to the GitHub-hosted label with the same OS image. */
export const RUNNER_MAP: Readonly<Record<string, string>> = {
  "depot-ubuntu-24.04": "ubuntu-24.04",
};

export const WORKFLOW_NAME_SUFFIX = " (fork fallback)";

export function forkJobName(id: string): string {
  return `fork / ${id}`;
}

export interface AdapterSpec {
  source: string;
  target: string;
}

export const ADAPTERS: readonly AdapterSpec[] = [
  { source: ".depot/workflows/ci.yml", target: ".github/workflows/fork-ci.yml" },
  { source: ".depot/workflows/contract.yml", target: ".github/workflows/fork-contract.yml" },
];

/** Untrusted fork code must never be given these, in either provider. */
const REFUSED_SOURCE_TEXT = [/\bsecrets\./, /\bpull_request_target\b/, /\bworkflow_run\b/];

function header(spec: AdapterSpec): string[] {
  return [
    `# GENERATED by scripts/fork-ci-adapters.ts from ${spec.source}. Do not edit.`,
    `# Change the Depot source, then run \`bun scripts/fork-ci-adapters.ts --write\`.`,
    "#",
    "# Depot CI does not receive pull requests from forks, so GitHub Actions runs",
    "# these gates for them, and only for them. Depot keeps same-repository PRs",
    "# and main. Adaptations: pull_request trigger only, fork-only job routing,",
    "# `fork / <job>` check names, GitHub-hosted runners and non-persisted",
    "# checkout credentials. See docs/decisions/claude-code-runtime.md,",
    '# "Fork pull requests fall back to GitHub Actions (#988)".',
    "",
  ];
}

const indentOf = (line: string) => line.length - line.trimStart().length;
const isBlankOrComment = (line: string) => line.trim() === "" || line.trimStart().startsWith("#");

/** The index of the first line after the block that starts at `start`. */
function blockEnd(lines: string[], start: number, indent: number): number {
  let end = start + 1;
  while (end < lines.length) {
    const line = lines[end]!;
    if (!isBlankOrComment(line) && indentOf(line) <= indent) break;
    end++;
  }
  // Trailing blank and comment lines belong to whatever follows.
  while (end > start + 1 && isBlankOrComment(lines[end - 1]!)) end--;
  return end;
}

function refuse(spec: AdapterSpec, message: string): never {
  throw new Error(`${spec.source}: ${message}`);
}

/** Derive the fork adapter's text from a Depot workflow's text. */
export function generateAdapter(sourceText: string, spec: AdapterSpec): string {
  for (const pattern of REFUSED_SOURCE_TEXT) {
    if (pattern.test(sourceText)) refuse(spec, `refusing to adapt a workflow that mentions ${pattern}`);
  }
  if (sourceText.includes("\t")) refuse(spec, "tab indentation is not supported");
  const lines = sourceText.replace(/\n$/, "").split("\n");
  const out: string[] = [];

  let sawName = false;
  let sawOn = false;
  let jobs = 0;
  let i = 0;
  while (i < lines.length) {
    const line = lines[i]!;
    if (isBlankOrComment(line) || indentOf(line) > 0) {
      out.push(line);
      i++;
      continue;
    }
    const key = /^([A-Za-z_-]+):(.*)$/.exec(line);
    if (!key) refuse(spec, `unrecognised top-level line ${i + 1}: ${line}`);
    const [, name, rest] = key;
    const end = blockEnd(lines, i, 0);
    if (name === "name") {
      if (rest!.trim() === "") refuse(spec, "the workflow name must be a scalar");
      out.push(`name: ${rest!.trim()}${WORKFLOW_NAME_SUFFIX}`);
      sawName = true;
    } else if (name === "on") {
      out.push(...adaptTriggers(lines.slice(i, end), spec));
      sawOn = true;
    } else if (name === "jobs") {
      const adapted = adaptJobs(lines.slice(i, end), spec);
      out.push(...adapted.lines);
      jobs = adapted.count;
    } else if (name === "permissions" || name === "concurrency" || name === "env") {
      out.push(...lines.slice(i, end));
    } else {
      refuse(spec, `top-level key \`${name}\` has no fork adaptation rule`);
    }
    i = end;
  }
  if (!sawName) refuse(spec, "the workflow has no name");
  if (!sawOn) refuse(spec, "the workflow has no triggers");
  if (jobs === 0) refuse(spec, "the workflow has no jobs");
  return [...header(spec), ...out].join("\n") + "\n";
}

/** Keep the `pull_request` trigger and its settings; drop `push`. */
function adaptTriggers(block: string[], spec: AdapterSpec): string[] {
  if (block[0] !== "on:") refuse(spec, "`on:` must be a mapping");
  const out = ["on:"];
  let sawPullRequest = false;
  let i = 1;
  while (i < block.length) {
    const line = block[i]!;
    if (isBlankOrComment(line)) {
      i++;
      continue;
    }
    if (indentOf(line) !== 2) refuse(spec, `unexpected trigger line: ${line}`);
    const end = blockEnd(block, i, 2);
    const event = /^ {2}([a-z_]+):/.exec(line)?.[1];
    if (event === "pull_request") {
      out.push(...block.slice(i, end));
      sawPullRequest = true;
    } else if (event !== "push") {
      refuse(spec, `trigger \`${event}\` has no fork adaptation rule`);
    }
    i = end;
  }
  if (!sawPullRequest) refuse(spec, "the workflow has no pull_request trigger to adapt");
  return out;
}

function adaptJobs(block: string[], spec: AdapterSpec): { lines: string[]; count: number } {
  const out = [block[0]!];
  let count = 0;
  let i = 1;
  while (i < block.length) {
    const line = block[i]!;
    if (isBlankOrComment(line)) {
      out.push(line);
      i++;
      continue;
    }
    const job = /^ {2}([A-Za-z0-9_-]+):\s*$/.exec(line);
    if (!job) refuse(spec, `unrecognised job line: ${line}`);
    const end = blockEnd(block, i, 2);
    out.push(...adaptJob(job[1]!, block.slice(i, end), spec));
    count++;
    i = end;
  }
  return { lines: out, count };
}

function adaptJob(id: string, block: string[], spec: AdapterSpec): string[] {
  const out = [block[0]!];
  let route = 0;
  let runner = 0;
  let checkouts = 0;
  for (let i = 1; i < block.length; i++) {
    const line = block[i]!;
    const jobKey = indentOf(line) === 4 && !isBlankOrComment(line) ? /^ {4}([a-z-]+):(.*)$/.exec(line) : null;
    if (jobKey?.[1] === "name") refuse(spec, `job ${id} sets its own name; add a naming rule first`);
    if (jobKey?.[1] === "permissions") refuse(spec, `job ${id} sets job permissions; add a rule first`);
    if (jobKey?.[1] === "if") {
      if (jobKey[2]!.trim() !== DEPOT_ROUTE) {
        refuse(spec, `job ${id} must be routed with \`if: ${DEPOT_ROUTE}\``);
      }
      out.push(`    name: ${forkJobName(id)}`, `    if: ${FORK_ROUTE}`);
      route++;
      continue;
    }
    if (jobKey?.[1] === "runs-on") {
      const label = jobKey[2]!.trim();
      const mapped = RUNNER_MAP[label];
      if (!mapped) refuse(spec, `job ${id} runs on \`${label}\`, which has no GitHub-hosted mapping`);
      out.push(`    runs-on: ${mapped}`);
      runner++;
      continue;
    }
    if (/persist-credentials/.test(line)) refuse(spec, `job ${id} already sets persist-credentials`);
    const checkout = /^(\s*)- uses: actions\/checkout@\S+\s*$/.exec(line);
    out.push(line);
    if (checkout) {
      const stepIndent = checkout[1]!.length + 2;
      const pad = " ".repeat(stepIndent);
      const next = block[i + 1];
      if (next !== undefined && next === `${pad}with:`) {
        out.push(next, `${pad}  persist-credentials: false`);
        i++;
      } else if (next !== undefined && next.startsWith(`${pad}with:`)) {
        refuse(spec, `job ${id} has a checkout \`with:\` this generator cannot extend`);
      } else {
        out.push(`${pad}with:`, `${pad}  persist-credentials: false`);
      }
      checkouts++;
    } else if (/actions\/checkout@/.test(line)) {
      refuse(spec, `job ${id} uses checkout in a form this generator cannot adapt: ${line.trim()}`);
    }
  }
  if (route !== 1) refuse(spec, `job ${id} must carry exactly one \`if: ${DEPOT_ROUTE}\``);
  if (runner !== 1) refuse(spec, `job ${id} must have exactly one runs-on label`);
  if (checkouts === 0) refuse(spec, `job ${id} has no actions/checkout step`);
  return out;
}

if (import.meta.main) {
  const mode = process.argv[2];
  // `bun run lint` passes the repository root; treat it like --check.
  const write = mode === "--write";
  if (mode !== undefined && mode !== "--write" && mode !== "--check" && !existsSync(mode)) {
    console.error("usage: bun scripts/fork-ci-adapters.ts [--check | --write]");
    process.exit(2);
  }
  let stale = false;
  for (const spec of ADAPTERS) {
    const expected = generateAdapter(readFileSync(join(ROOT, spec.source), "utf8"), spec);
    const targetPath = join(ROOT, spec.target);
    const actual = existsSync(targetPath) ? readFileSync(targetPath, "utf8") : null;
    if (actual === expected) continue;
    if (write) {
      writeFileSync(targetPath, expected);
      console.log(`wrote ${spec.target}`);
    } else {
      console.error(`${spec.target} is stale against ${spec.source}.`);
      stale = true;
    }
  }
  if (stale) {
    console.error("Run `bun scripts/fork-ci-adapters.ts --write` and commit the result.");
    process.exit(1);
  }
  if (!write) console.log("fork CI adapters match their Depot sources.");
}
