/**
 * Regenerate packages/core/src/lib/case-fold.ts from a Unicode CaseFolding.txt.
 *
 *   curl -O https://www.unicode.org/Public/16.0.0/ucd/CaseFolding.txt
 *   bun scripts/gen-case-fold.ts CaseFolding.txt
 *
 * Unicode full case folding is the C and F rows. JavaScript has no fold, but
 * `toLowerCase` agrees with it for almost every code point, so the module
 * stores only the code points where they differ (ß, ς, the Greek iota
 * subscripts, Cherokee, …) and lowercases the rest.
 */

import { writeFileSync } from "fs";
import { join } from "path";

const source = process.argv[2];
if (!source) {
  console.error("usage: bun scripts/gen-case-fold.ts <CaseFolding.txt>");
  process.exit(1);
}
const text = await Bun.file(source).text();
const version = text.match(/^# CaseFolding-(\d+\.\d+\.\d+)\.txt/)?.[1];
if (!version) throw new Error(`${source} does not look like CaseFolding.txt`);

const hex = (cp: number) => cp.toString(16).toUpperCase().padStart(4, "0");
const fold = new Map<number, number[]>();
for (const line of text.split("\n")) {
  const m = line.match(/^([0-9A-F]+); ([CF]); ([0-9A-F ]+);/);
  if (m) fold.set(parseInt(m[1], 16), m[3].trim().split(" ").map((h) => parseInt(h, 16)));
}

const entries: string[] = [];
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  const target = fold.get(cp) ?? [cp];
  const char = String.fromCodePoint(cp);
  if (char.toLowerCase() !== String.fromCodePoint(...target)) {
    entries.push(`${hex(cp)}:${target.map(hex).join(" ")}`);
  }
}

const lines: string[] = [];
for (let i = 0; i < entries.length; i += 8) lines.push(`  "${entries.slice(i, i + 8).join(",")}"`);

const out = `// Generated by scripts/gen-case-fold.ts from Unicode ${version} CaseFolding.txt.
// Do not edit by hand; rerun the script against a newer file instead.

/**
 * Code points whose Unicode full case folding (C and F rows) differs from
 * \`toLowerCase\`, as \`code:fold fold…\` in hex. Everything else folds to its
 * lowercase.
 */
const FOLD_DIFFERENCES = [
${lines.join(",\n")},
].join(",");

let table: Map<string, string> | undefined;

function differences(): Map<string, string> {
  if (!table) {
    table = new Map();
    for (const entry of FOLD_DIFFERENCES.split(",")) {
      const [from, to] = entry.split(":");
      table.set(
        String.fromCodePoint(parseInt(from, 16)),
        String.fromCodePoint(...to.split(" ").map((h) => parseInt(h, 16)))
      );
    }
  }
  return table;
}

/**
 * Canonical caseless form (Unicode §3.13, D145): NFD, full case folding, NFD.
 * Two strings match caselessly when their forms are equal.
 */
export function caseFold(text: string): string {
  const fold = differences();
  let out = "";
  for (const char of text.normalize("NFD")) out += fold.get(char) ?? char.toLowerCase();
  return out.normalize("NFD");
}
`;
writeFileSync(join(import.meta.dir, "../packages/core/src/lib/case-fold.ts"), out);
console.log(`wrote ${entries.length} differences from Unicode ${version}`);
