import preview from "#.storybook/preview";

import { straitChoice } from "../../fixtures/projects.js";
import { digestStats } from "../../fixtures/events.js";
import { spendTrend, crewTable, weekSpend } from "../../fixtures/money.js";
import { fetchReceipt } from "../../fixtures/runs.js";
import { straitSteps, forecastQuote } from "../../fixtures/notes.js";
import { overnight, today } from "../../fixtures/events.js";
import { penelopeFacts } from "../../fixtures/people.js";
import { ContactCard } from "../../src/blocks/ContactCard.js";
import { QuoteCard } from "../../src/blocks/QuoteCard.js";
import { ScheduleList } from "../../src/blocks/ScheduleList.js";
import { StatTiles } from "../../src/blocks/StatTiles.js";
import { StepList } from "../../src/blocks/StepList.js";
import { TimelineList } from "../../src/blocks/TimelineList.js";
import { TrendChart } from "../../src/blocks/TrendChart.js";
import { ComparisonTable } from "../../src/conversation/ComparisonTable.js";
import { BarList } from "../../src/evidence/BarList.js";
import { DataTable } from "../../src/evidence/DataTable.js";
import { Receipt } from "../../src/evidence/Receipt.js";

/**
 * Every answer block in the print theme: what a shared PNG or PDF draws (#46).
 *
 * `[data-theme="print"]` re-points every token to a plain value generated by
 * `tools/theme/derive-print.ts`: a white ground, no washes, borders that carry
 * the structure, the light theme's ink. The story pins the theme global, so
 * both Vitest story projects render it in print, and the a11y gate at
 * `'error'` is the print palette's contrast check.
 *
 * The column is at most 640px, about the width the share renderer lays a
 * message out at, and narrower where the viewport is.
 */
const meta = preview.meta({
  title: "Blocks/In print",
  parameters: { layout: "padded" },
  globals: { theme: "print" },
});

const blocks: [string, React.ReactNode][] = [
  [
    "comparison",
    <ComparisonTable
      {...straitChoice}
      footnote="Six men is the price of the ship. The other column has no price, only a chance."
    />,
  ],
  ["stats", <StatTiles tiles={digestStats} />],
  ["trend", <TrendChart {...spendTrend} />],
  ["table", <DataTable columns={crewTable.columns} rows={crewTable.rows} />],
  ["bars", <BarList rows={weekSpend} barWidth={74} />],
  [
    "receipt",
    <Receipt
      title="Capability you'd grant"
      titleIcon="capability"
      titleTone="amber"
      rows={fetchReceipt.rows}
      footnote={fetchReceipt.footnote}
      footIcon="scope"
      footTone="teal"
    />,
  ],
  ["steps", <StepList steps={straitSteps} variant="numbered" />],
  ["timeline", <TimelineList items={overnight} />],
  ["schedule", <ScheduleList groups={today} />],
  ["quote", <QuoteCard {...forecastQuote} />],
  ["contact", <ContactCard label="Penelope" role="Wife · holding Ithaca" kind="person" facts={penelopeFacts} />],
];

function Column({ kinds }: { kinds: string[] }) {
  return (
    <div
      style={{
        width: "100%",
        maxWidth: 640,
        boxSizing: "border-box",
        display: "flex",
        flexDirection: "column",
        gap: 20,
        background: "var(--bk-color-canvas)",
      }}
    >
      {blocks
        .filter(([kind]) => kinds.includes(kind))
        .map(([kind, block]) => (
          <div key={kind} data-block={kind}>
            {block}
          </div>
        ))}
    </div>
  );
}

const ALL = blocks.map(([kind]) => kind);

/** All eleven kinds, in the order `show_block` lists them. */
export const AllBlocks = meta.story({ render: () => <Column kinds={ALL} /> });

/**
 * The same eleven in four parts, each short enough to fit one screen: a
 * screenshot paints what is in the viewport, so the visual baselines take
 * these rather than the long column.
 */
export const Figures = meta.story({ render: () => <Column kinds={["comparison", "stats", "trend", "table"]} /> });
export const Records = meta.story({ render: () => <Column kinds={["bars", "receipt", "steps"]} /> });
export const Events = meta.story({ render: () => <Column kinds={["timeline", "schedule"]} /> });
export const People = meta.story({ render: () => <Column kinds={["quote", "contact"]} /> });
